name: Setup AWS Resources for Terraform

on:
  push:
    branches:
      - main

jobs:
  setup-aws-resources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create S3 bucket for Terraform state
      run: |
        aws s3api create-bucket --bucket bandzzz-terraform-state-bucket-202501 --region us-east-1
