name: Terraform Version Check

on:
  push:
    branches:
      - main

jobs:
  terraform-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Замените на нужную версию Terraform

      - name: Check Terraform Version
        run: terraform --version
